### ISSUE TITLE
Update to latest version of `glob`

### ISSUE THREAD

**Issue by adambuczynski** [node-js-libs/cli#83]
Could you update your package to use the latest version of `glob`?

The version currently used by `cli` uses an outdated `minimatch` which is throwing deprecation warnings:

```
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

**Comment by jtrees** [comment]
I came here to report the same thing.

**Comment by codeuniquely** [comment]
+1

**Comment by holm** [comment]
Would be great to have this updated and a new version published
