### ISSUE TITLE
Similar to tj/commander

### ISSUE THREAD

**Issue by goatandsheep** [node-js-libs/cli#87]
What is the difference between this and [tj/commander.js](https://github.com/tj/commander.js)? Should the two projects be merged?

**Comment by brownpride** [comment]
this library and commander have different scope.  commander only deals with arguments while cli also does stuff like printing progress bars

**Comment by goatandsheep** [comment]
That's fair. I was just thinking you could add to his package, but I don't think it's useful to bloat his package with things when not everyone needs that.
